# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Swapnil Gupta
tagline:          'Discovering myself'
description:      'I write my thoughts on self-discovery here'
baseurl:          /

author:
  name:           'Swapnil Gupta'
  url:            https://twitter.com/swapnilgt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/swapnilgt
